apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: debugging-cloud-apps
build:
  local:
    useBuildkit: true
  artifacts:
    - image: ghcr.io/antoniomartinez/api
      context: .
      ko:
        main: ./cmd/api
manifests:
  rawYaml:
    - tests/api.yaml

portForward:
  - resourceType: service
    resourceName: antonio-api
    namespace: default
    port: 8080
    localPort: 8080 # *Optional*

profiles:
  - name: local
    activation:
      - command: dev
        kubeContext: kind-kind
    patches:
      - op: add
        path: /build/artifacts/-
        value:
          image: cloud-provider-kind
          # need to use custom build command since skaffold docker builder does not support remote context
          custom:
            buildCommand: |
              docker build -t $IMAGE https://github.com/kubernetes-sigs/cloud-provider-kind.git#main
      - op: add
        path: /manifests/rawYaml/-
        value: tests/cloud-provider-kind.yaml
